<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\CatalogDeJocuri\App.config" Link="App.config" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CatalogDeJocuri\CatalogDeJocuri.csproj" />
    <ProjectReference Include="..\EnumGestionare\EnumGestionare.csproj" />
    <ProjectReference Include="..\Joc\DespreJoc.csproj" />
    <ProjectReference Include="..\StocareJocurilor\StocareJocurilor.csproj" />
  </ItemGroup>

</Project>
